# Generated from bgvoice/v1/pipeline.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .pipeline_pb2 import Campaign, Character, CharacterClass, CharacterSound, Dialogue, DialogueLine, DialogueTransition, DownloadPortraitRequest, ExtractionRun, GetCampaignRequest, GetCharacterClassRequest, GetCharacterRequest, GetCharacterSoundRequest, GetDialogueLineRequest, GetDialogueRequest, GetDialogueTransitionRequest, GetExtractionRunRequest, GetIdentifierDefinitionRequest, GetInstallationRequest, GetKitRequest, GetPortraitRequest, GetRaceRequest, GetVoiceRequest, IdentifierDefinition, Installation, Kit, ListCampaignsRequest, ListCampaignsResponse, ListCharacterClassesRequest, ListCharacterClassesResponse, ListCharacterSoundsRequest, ListCharacterSoundsResponse, ListCharactersRequest, ListCharactersResponse, ListDialogueLinesRequest, ListDialogueLinesResponse, ListDialogueTransitionsRequest, ListDialogueTransitionsResponse, ListDialoguesRequest, ListDialoguesResponse, ListExtractionRunsRequest, ListExtractionRunsResponse, ListIdentifierDefinitionsRequest, ListIdentifierDefinitionsResponse, ListKitsRequest, ListKitsResponse, ListPortraitsRequest, ListPortraitsResponse, ListRacesRequest, ListRacesResponse, ListVoicesRequest, ListVoicesResponse, Portrait, PortraitContent, Race, Voice

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class PipelineService(Protocol):
    async def get_installation(self, request: GetInstallationRequest, ctx: RequestContext[GetInstallationRequest, Installation]) -> Installation:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_voices(self, request: ListVoicesRequest, ctx: RequestContext[ListVoicesRequest, ListVoicesResponse]) -> ListVoicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_voice(self, request: GetVoiceRequest, ctx: RequestContext[GetVoiceRequest, Voice]) -> Voice:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_characters(self, request: ListCharactersRequest, ctx: RequestContext[ListCharactersRequest, ListCharactersResponse]) -> ListCharactersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_character(self, request: GetCharacterRequest, ctx: RequestContext[GetCharacterRequest, Character]) -> Character:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_dialogues(self, request: ListDialoguesRequest, ctx: RequestContext[ListDialoguesRequest, ListDialoguesResponse]) -> ListDialoguesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_dialogue(self, request: GetDialogueRequest, ctx: RequestContext[GetDialogueRequest, Dialogue]) -> Dialogue:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_dialogue_lines(self, request: ListDialogueLinesRequest, ctx: RequestContext[ListDialogueLinesRequest, ListDialogueLinesResponse]) -> ListDialogueLinesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_dialogue_line(self, request: GetDialogueLineRequest, ctx: RequestContext[GetDialogueLineRequest, DialogueLine]) -> DialogueLine:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_character_sounds(self, request: ListCharacterSoundsRequest, ctx: RequestContext[ListCharacterSoundsRequest, ListCharacterSoundsResponse]) -> ListCharacterSoundsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_character_sound(self, request: GetCharacterSoundRequest, ctx: RequestContext[GetCharacterSoundRequest, CharacterSound]) -> CharacterSound:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_dialogue_transitions(self, request: ListDialogueTransitionsRequest, ctx: RequestContext[ListDialogueTransitionsRequest, ListDialogueTransitionsResponse]) -> ListDialogueTransitionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_dialogue_transition(self, request: GetDialogueTransitionRequest, ctx: RequestContext[GetDialogueTransitionRequest, DialogueTransition]) -> DialogueTransition:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_portraits(self, request: ListPortraitsRequest, ctx: RequestContext[ListPortraitsRequest, ListPortraitsResponse]) -> ListPortraitsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_portrait(self, request: GetPortraitRequest, ctx: RequestContext[GetPortraitRequest, Portrait]) -> Portrait:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def download_portrait(self, request: DownloadPortraitRequest, ctx: RequestContext[DownloadPortraitRequest, PortraitContent]) -> PortraitContent:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_races(self, request: ListRacesRequest, ctx: RequestContext[ListRacesRequest, ListRacesResponse]) -> ListRacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_race(self, request: GetRaceRequest, ctx: RequestContext[GetRaceRequest, Race]) -> Race:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_character_classes(self, request: ListCharacterClassesRequest, ctx: RequestContext[ListCharacterClassesRequest, ListCharacterClassesResponse]) -> ListCharacterClassesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_character_class(self, request: GetCharacterClassRequest, ctx: RequestContext[GetCharacterClassRequest, CharacterClass]) -> CharacterClass:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_kits(self, request: ListKitsRequest, ctx: RequestContext[ListKitsRequest, ListKitsResponse]) -> ListKitsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_kit(self, request: GetKitRequest, ctx: RequestContext[GetKitRequest, Kit]) -> Kit:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_identifier_definitions(self, request: ListIdentifierDefinitionsRequest, ctx: RequestContext[ListIdentifierDefinitionsRequest, ListIdentifierDefinitionsResponse]) -> ListIdentifierDefinitionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_identifier_definition(self, request: GetIdentifierDefinitionRequest, ctx: RequestContext[GetIdentifierDefinitionRequest, IdentifierDefinition]) -> IdentifierDefinition:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_campaigns(self, request: ListCampaignsRequest, ctx: RequestContext[ListCampaignsRequest, ListCampaignsResponse]) -> ListCampaignsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_campaign(self, request: GetCampaignRequest, ctx: RequestContext[GetCampaignRequest, Campaign]) -> Campaign:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_extraction_runs(self, request: ListExtractionRunsRequest, ctx: RequestContext[ListExtractionRunsRequest, ListExtractionRunsResponse]) -> ListExtractionRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_extraction_run(self, request: GetExtractionRunRequest, ctx: RequestContext[GetExtractionRunRequest, ExtractionRun]) -> ExtractionRun:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PipelineServiceASGIApplication(ConnectASGIApplication[PipelineService]):
    def __init__(
        self,
        service: PipelineService | AsyncGenerator[PipelineService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/bgvoice.v1.PipelineService/GetInstallation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInstallation",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetInstallationRequest,
                        output=Installation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_installation,
                ),
                "/bgvoice.v1.PipelineService/ListVoices": Endpoint.unary(
                    method=MethodInfo(
                        name="ListVoices",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListVoicesRequest,
                        output=ListVoicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_voices,
                ),
                "/bgvoice.v1.PipelineService/GetVoice": Endpoint.unary(
                    method=MethodInfo(
                        name="GetVoice",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetVoiceRequest,
                        output=Voice,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_voice,
                ),
                "/bgvoice.v1.PipelineService/ListCharacters": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCharacters",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharactersRequest,
                        output=ListCharactersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_characters,
                ),
                "/bgvoice.v1.PipelineService/GetCharacter": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCharacter",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterRequest,
                        output=Character,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_character,
                ),
                "/bgvoice.v1.PipelineService/ListDialogues": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDialogues",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialoguesRequest,
                        output=ListDialoguesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_dialogues,
                ),
                "/bgvoice.v1.PipelineService/GetDialogue": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDialogue",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueRequest,
                        output=Dialogue,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_dialogue,
                ),
                "/bgvoice.v1.PipelineService/ListDialogueLines": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDialogueLines",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialogueLinesRequest,
                        output=ListDialogueLinesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_dialogue_lines,
                ),
                "/bgvoice.v1.PipelineService/GetDialogueLine": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDialogueLine",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueLineRequest,
                        output=DialogueLine,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_dialogue_line,
                ),
                "/bgvoice.v1.PipelineService/ListCharacterSounds": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCharacterSounds",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharacterSoundsRequest,
                        output=ListCharacterSoundsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_character_sounds,
                ),
                "/bgvoice.v1.PipelineService/GetCharacterSound": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCharacterSound",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterSoundRequest,
                        output=CharacterSound,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_character_sound,
                ),
                "/bgvoice.v1.PipelineService/ListDialogueTransitions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDialogueTransitions",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialogueTransitionsRequest,
                        output=ListDialogueTransitionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_dialogue_transitions,
                ),
                "/bgvoice.v1.PipelineService/GetDialogueTransition": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDialogueTransition",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueTransitionRequest,
                        output=DialogueTransition,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_dialogue_transition,
                ),
                "/bgvoice.v1.PipelineService/ListPortraits": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPortraits",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListPortraitsRequest,
                        output=ListPortraitsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_portraits,
                ),
                "/bgvoice.v1.PipelineService/GetPortrait": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPortrait",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetPortraitRequest,
                        output=Portrait,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_portrait,
                ),
                "/bgvoice.v1.PipelineService/DownloadPortrait": Endpoint.unary(
                    method=MethodInfo(
                        name="DownloadPortrait",
                        service_name="bgvoice.v1.PipelineService",
                        input=DownloadPortraitRequest,
                        output=PortraitContent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.download_portrait,
                ),
                "/bgvoice.v1.PipelineService/ListRaces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRaces",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListRacesRequest,
                        output=ListRacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_races,
                ),
                "/bgvoice.v1.PipelineService/GetRace": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRace",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetRaceRequest,
                        output=Race,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_race,
                ),
                "/bgvoice.v1.PipelineService/ListCharacterClasses": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCharacterClasses",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharacterClassesRequest,
                        output=ListCharacterClassesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_character_classes,
                ),
                "/bgvoice.v1.PipelineService/GetCharacterClass": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCharacterClass",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterClassRequest,
                        output=CharacterClass,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_character_class,
                ),
                "/bgvoice.v1.PipelineService/ListKits": Endpoint.unary(
                    method=MethodInfo(
                        name="ListKits",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListKitsRequest,
                        output=ListKitsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_kits,
                ),
                "/bgvoice.v1.PipelineService/GetKit": Endpoint.unary(
                    method=MethodInfo(
                        name="GetKit",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetKitRequest,
                        output=Kit,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_kit,
                ),
                "/bgvoice.v1.PipelineService/ListIdentifierDefinitions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListIdentifierDefinitions",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListIdentifierDefinitionsRequest,
                        output=ListIdentifierDefinitionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_identifier_definitions,
                ),
                "/bgvoice.v1.PipelineService/GetIdentifierDefinition": Endpoint.unary(
                    method=MethodInfo(
                        name="GetIdentifierDefinition",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetIdentifierDefinitionRequest,
                        output=IdentifierDefinition,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_identifier_definition,
                ),
                "/bgvoice.v1.PipelineService/ListCampaigns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCampaigns",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCampaignsRequest,
                        output=ListCampaignsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_campaigns,
                ),
                "/bgvoice.v1.PipelineService/GetCampaign": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCampaign",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCampaignRequest,
                        output=Campaign,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_campaign,
                ),
                "/bgvoice.v1.PipelineService/ListExtractionRuns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListExtractionRuns",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListExtractionRunsRequest,
                        output=ListExtractionRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_extraction_runs,
                ),
                "/bgvoice.v1.PipelineService/GetExtractionRun": Endpoint.unary(
                    method=MethodInfo(
                        name="GetExtractionRun",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetExtractionRunRequest,
                        output=ExtractionRun,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_extraction_run,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bgvoice.v1.PipelineService"


class PipelineServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_installation(
        self,
        request: GetInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Installation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstallation",
                service_name="bgvoice.v1.PipelineService",
                input=GetInstallationRequest,
                output=Installation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_voices(
        self,
        request: ListVoicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListVoicesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListVoices",
                service_name="bgvoice.v1.PipelineService",
                input=ListVoicesRequest,
                output=ListVoicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_voice(
        self,
        request: GetVoiceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Voice:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetVoice",
                service_name="bgvoice.v1.PipelineService",
                input=GetVoiceRequest,
                output=Voice,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_characters(
        self,
        request: ListCharactersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharactersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacters",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharactersRequest,
                output=ListCharactersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_character(
        self,
        request: GetCharacterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Character:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacter",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterRequest,
                output=Character,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_dialogues(
        self,
        request: ListDialoguesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialoguesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogues",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialoguesRequest,
                output=ListDialoguesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_dialogue(
        self,
        request: GetDialogueRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Dialogue:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogue",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueRequest,
                output=Dialogue,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_dialogue_lines(
        self,
        request: ListDialogueLinesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialogueLinesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogueLines",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialogueLinesRequest,
                output=ListDialogueLinesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_dialogue_line(
        self,
        request: GetDialogueLineRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DialogueLine:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogueLine",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueLineRequest,
                output=DialogueLine,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_character_sounds(
        self,
        request: ListCharacterSoundsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharacterSoundsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacterSounds",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharacterSoundsRequest,
                output=ListCharacterSoundsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_character_sound(
        self,
        request: GetCharacterSoundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CharacterSound:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacterSound",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterSoundRequest,
                output=CharacterSound,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_dialogue_transitions(
        self,
        request: ListDialogueTransitionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialogueTransitionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogueTransitions",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialogueTransitionsRequest,
                output=ListDialogueTransitionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_dialogue_transition(
        self,
        request: GetDialogueTransitionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DialogueTransition:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogueTransition",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueTransitionRequest,
                output=DialogueTransition,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_portraits(
        self,
        request: ListPortraitsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListPortraitsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPortraits",
                service_name="bgvoice.v1.PipelineService",
                input=ListPortraitsRequest,
                output=ListPortraitsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_portrait(
        self,
        request: GetPortraitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Portrait:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPortrait",
                service_name="bgvoice.v1.PipelineService",
                input=GetPortraitRequest,
                output=Portrait,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def download_portrait(
        self,
        request: DownloadPortraitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PortraitContent:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DownloadPortrait",
                service_name="bgvoice.v1.PipelineService",
                input=DownloadPortraitRequest,
                output=PortraitContent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_races(
        self,
        request: ListRacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRacesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRaces",
                service_name="bgvoice.v1.PipelineService",
                input=ListRacesRequest,
                output=ListRacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_race(
        self,
        request: GetRaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Race:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRace",
                service_name="bgvoice.v1.PipelineService",
                input=GetRaceRequest,
                output=Race,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_character_classes(
        self,
        request: ListCharacterClassesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharacterClassesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacterClasses",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharacterClassesRequest,
                output=ListCharacterClassesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_character_class(
        self,
        request: GetCharacterClassRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CharacterClass:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacterClass",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterClassRequest,
                output=CharacterClass,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_kits(
        self,
        request: ListKitsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListKitsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKits",
                service_name="bgvoice.v1.PipelineService",
                input=ListKitsRequest,
                output=ListKitsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_kit(
        self,
        request: GetKitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Kit:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKit",
                service_name="bgvoice.v1.PipelineService",
                input=GetKitRequest,
                output=Kit,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_identifier_definitions(
        self,
        request: ListIdentifierDefinitionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListIdentifierDefinitionsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListIdentifierDefinitions",
                service_name="bgvoice.v1.PipelineService",
                input=ListIdentifierDefinitionsRequest,
                output=ListIdentifierDefinitionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_identifier_definition(
        self,
        request: GetIdentifierDefinitionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> IdentifierDefinition:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetIdentifierDefinition",
                service_name="bgvoice.v1.PipelineService",
                input=GetIdentifierDefinitionRequest,
                output=IdentifierDefinition,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_campaigns(
        self,
        request: ListCampaignsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCampaignsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCampaigns",
                service_name="bgvoice.v1.PipelineService",
                input=ListCampaignsRequest,
                output=ListCampaignsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_campaign(
        self,
        request: GetCampaignRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Campaign:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCampaign",
                service_name="bgvoice.v1.PipelineService",
                input=GetCampaignRequest,
                output=Campaign,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_extraction_runs(
        self,
        request: ListExtractionRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListExtractionRunsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListExtractionRuns",
                service_name="bgvoice.v1.PipelineService",
                input=ListExtractionRunsRequest,
                output=ListExtractionRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_extraction_run(
        self,
        request: GetExtractionRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExtractionRun:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetExtractionRun",
                service_name="bgvoice.v1.PipelineService",
                input=GetExtractionRunRequest,
                output=ExtractionRun,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class PipelineServiceSync(Protocol):
    def get_installation(self, request: GetInstallationRequest, ctx: RequestContext[GetInstallationRequest, Installation]) -> Installation:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_voices(self, request: ListVoicesRequest, ctx: RequestContext[ListVoicesRequest, ListVoicesResponse]) -> ListVoicesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_voice(self, request: GetVoiceRequest, ctx: RequestContext[GetVoiceRequest, Voice]) -> Voice:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_characters(self, request: ListCharactersRequest, ctx: RequestContext[ListCharactersRequest, ListCharactersResponse]) -> ListCharactersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_character(self, request: GetCharacterRequest, ctx: RequestContext[GetCharacterRequest, Character]) -> Character:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_dialogues(self, request: ListDialoguesRequest, ctx: RequestContext[ListDialoguesRequest, ListDialoguesResponse]) -> ListDialoguesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_dialogue(self, request: GetDialogueRequest, ctx: RequestContext[GetDialogueRequest, Dialogue]) -> Dialogue:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_dialogue_lines(self, request: ListDialogueLinesRequest, ctx: RequestContext[ListDialogueLinesRequest, ListDialogueLinesResponse]) -> ListDialogueLinesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_dialogue_line(self, request: GetDialogueLineRequest, ctx: RequestContext[GetDialogueLineRequest, DialogueLine]) -> DialogueLine:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_character_sounds(self, request: ListCharacterSoundsRequest, ctx: RequestContext[ListCharacterSoundsRequest, ListCharacterSoundsResponse]) -> ListCharacterSoundsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_character_sound(self, request: GetCharacterSoundRequest, ctx: RequestContext[GetCharacterSoundRequest, CharacterSound]) -> CharacterSound:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_dialogue_transitions(self, request: ListDialogueTransitionsRequest, ctx: RequestContext[ListDialogueTransitionsRequest, ListDialogueTransitionsResponse]) -> ListDialogueTransitionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_dialogue_transition(self, request: GetDialogueTransitionRequest, ctx: RequestContext[GetDialogueTransitionRequest, DialogueTransition]) -> DialogueTransition:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_portraits(self, request: ListPortraitsRequest, ctx: RequestContext[ListPortraitsRequest, ListPortraitsResponse]) -> ListPortraitsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_portrait(self, request: GetPortraitRequest, ctx: RequestContext[GetPortraitRequest, Portrait]) -> Portrait:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def download_portrait(self, request: DownloadPortraitRequest, ctx: RequestContext[DownloadPortraitRequest, PortraitContent]) -> PortraitContent:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_races(self, request: ListRacesRequest, ctx: RequestContext[ListRacesRequest, ListRacesResponse]) -> ListRacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_race(self, request: GetRaceRequest, ctx: RequestContext[GetRaceRequest, Race]) -> Race:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_character_classes(self, request: ListCharacterClassesRequest, ctx: RequestContext[ListCharacterClassesRequest, ListCharacterClassesResponse]) -> ListCharacterClassesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_character_class(self, request: GetCharacterClassRequest, ctx: RequestContext[GetCharacterClassRequest, CharacterClass]) -> CharacterClass:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_kits(self, request: ListKitsRequest, ctx: RequestContext[ListKitsRequest, ListKitsResponse]) -> ListKitsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_kit(self, request: GetKitRequest, ctx: RequestContext[GetKitRequest, Kit]) -> Kit:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_identifier_definitions(self, request: ListIdentifierDefinitionsRequest, ctx: RequestContext[ListIdentifierDefinitionsRequest, ListIdentifierDefinitionsResponse]) -> ListIdentifierDefinitionsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_identifier_definition(self, request: GetIdentifierDefinitionRequest, ctx: RequestContext[GetIdentifierDefinitionRequest, IdentifierDefinition]) -> IdentifierDefinition:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_campaigns(self, request: ListCampaignsRequest, ctx: RequestContext[ListCampaignsRequest, ListCampaignsResponse]) -> ListCampaignsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_campaign(self, request: GetCampaignRequest, ctx: RequestContext[GetCampaignRequest, Campaign]) -> Campaign:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_extraction_runs(self, request: ListExtractionRunsRequest, ctx: RequestContext[ListExtractionRunsRequest, ListExtractionRunsResponse]) -> ListExtractionRunsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_extraction_run(self, request: GetExtractionRunRequest, ctx: RequestContext[GetExtractionRunRequest, ExtractionRun]) -> ExtractionRun:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PipelineServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: PipelineServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/bgvoice.v1.PipelineService/GetInstallation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetInstallation",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetInstallationRequest,
                        output=Installation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_installation,
                ),
                "/bgvoice.v1.PipelineService/ListVoices": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListVoices",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListVoicesRequest,
                        output=ListVoicesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_voices,
                ),
                "/bgvoice.v1.PipelineService/GetVoice": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetVoice",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetVoiceRequest,
                        output=Voice,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_voice,
                ),
                "/bgvoice.v1.PipelineService/ListCharacters": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCharacters",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharactersRequest,
                        output=ListCharactersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_characters,
                ),
                "/bgvoice.v1.PipelineService/GetCharacter": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCharacter",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterRequest,
                        output=Character,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_character,
                ),
                "/bgvoice.v1.PipelineService/ListDialogues": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDialogues",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialoguesRequest,
                        output=ListDialoguesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_dialogues,
                ),
                "/bgvoice.v1.PipelineService/GetDialogue": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDialogue",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueRequest,
                        output=Dialogue,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_dialogue,
                ),
                "/bgvoice.v1.PipelineService/ListDialogueLines": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDialogueLines",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialogueLinesRequest,
                        output=ListDialogueLinesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_dialogue_lines,
                ),
                "/bgvoice.v1.PipelineService/GetDialogueLine": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDialogueLine",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueLineRequest,
                        output=DialogueLine,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_dialogue_line,
                ),
                "/bgvoice.v1.PipelineService/ListCharacterSounds": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCharacterSounds",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharacterSoundsRequest,
                        output=ListCharacterSoundsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_character_sounds,
                ),
                "/bgvoice.v1.PipelineService/GetCharacterSound": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCharacterSound",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterSoundRequest,
                        output=CharacterSound,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_character_sound,
                ),
                "/bgvoice.v1.PipelineService/ListDialogueTransitions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDialogueTransitions",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListDialogueTransitionsRequest,
                        output=ListDialogueTransitionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_dialogue_transitions,
                ),
                "/bgvoice.v1.PipelineService/GetDialogueTransition": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDialogueTransition",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetDialogueTransitionRequest,
                        output=DialogueTransition,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_dialogue_transition,
                ),
                "/bgvoice.v1.PipelineService/ListPortraits": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPortraits",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListPortraitsRequest,
                        output=ListPortraitsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_portraits,
                ),
                "/bgvoice.v1.PipelineService/GetPortrait": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPortrait",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetPortraitRequest,
                        output=Portrait,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_portrait,
                ),
                "/bgvoice.v1.PipelineService/DownloadPortrait": EndpointSync.unary(
                    method=MethodInfo(
                        name="DownloadPortrait",
                        service_name="bgvoice.v1.PipelineService",
                        input=DownloadPortraitRequest,
                        output=PortraitContent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.download_portrait,
                ),
                "/bgvoice.v1.PipelineService/ListRaces": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRaces",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListRacesRequest,
                        output=ListRacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_races,
                ),
                "/bgvoice.v1.PipelineService/GetRace": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRace",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetRaceRequest,
                        output=Race,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_race,
                ),
                "/bgvoice.v1.PipelineService/ListCharacterClasses": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCharacterClasses",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCharacterClassesRequest,
                        output=ListCharacterClassesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_character_classes,
                ),
                "/bgvoice.v1.PipelineService/GetCharacterClass": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCharacterClass",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCharacterClassRequest,
                        output=CharacterClass,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_character_class,
                ),
                "/bgvoice.v1.PipelineService/ListKits": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListKits",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListKitsRequest,
                        output=ListKitsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_kits,
                ),
                "/bgvoice.v1.PipelineService/GetKit": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetKit",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetKitRequest,
                        output=Kit,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_kit,
                ),
                "/bgvoice.v1.PipelineService/ListIdentifierDefinitions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListIdentifierDefinitions",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListIdentifierDefinitionsRequest,
                        output=ListIdentifierDefinitionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_identifier_definitions,
                ),
                "/bgvoice.v1.PipelineService/GetIdentifierDefinition": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetIdentifierDefinition",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetIdentifierDefinitionRequest,
                        output=IdentifierDefinition,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_identifier_definition,
                ),
                "/bgvoice.v1.PipelineService/ListCampaigns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCampaigns",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListCampaignsRequest,
                        output=ListCampaignsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_campaigns,
                ),
                "/bgvoice.v1.PipelineService/GetCampaign": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCampaign",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetCampaignRequest,
                        output=Campaign,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_campaign,
                ),
                "/bgvoice.v1.PipelineService/ListExtractionRuns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListExtractionRuns",
                        service_name="bgvoice.v1.PipelineService",
                        input=ListExtractionRunsRequest,
                        output=ListExtractionRunsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_extraction_runs,
                ),
                "/bgvoice.v1.PipelineService/GetExtractionRun": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetExtractionRun",
                        service_name="bgvoice.v1.PipelineService",
                        input=GetExtractionRunRequest,
                        output=ExtractionRun,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_extraction_run,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/bgvoice.v1.PipelineService"


class PipelineServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_installation(
        self,
        request: GetInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Installation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstallation",
                service_name="bgvoice.v1.PipelineService",
                input=GetInstallationRequest,
                output=Installation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_voices(
        self,
        request: ListVoicesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListVoicesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListVoices",
                service_name="bgvoice.v1.PipelineService",
                input=ListVoicesRequest,
                output=ListVoicesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_voice(
        self,
        request: GetVoiceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Voice:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetVoice",
                service_name="bgvoice.v1.PipelineService",
                input=GetVoiceRequest,
                output=Voice,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_characters(
        self,
        request: ListCharactersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharactersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacters",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharactersRequest,
                output=ListCharactersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_character(
        self,
        request: GetCharacterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Character:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacter",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterRequest,
                output=Character,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_dialogues(
        self,
        request: ListDialoguesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialoguesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogues",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialoguesRequest,
                output=ListDialoguesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_dialogue(
        self,
        request: GetDialogueRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Dialogue:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogue",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueRequest,
                output=Dialogue,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_dialogue_lines(
        self,
        request: ListDialogueLinesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialogueLinesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogueLines",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialogueLinesRequest,
                output=ListDialogueLinesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_dialogue_line(
        self,
        request: GetDialogueLineRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DialogueLine:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogueLine",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueLineRequest,
                output=DialogueLine,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_character_sounds(
        self,
        request: ListCharacterSoundsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharacterSoundsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacterSounds",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharacterSoundsRequest,
                output=ListCharacterSoundsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_character_sound(
        self,
        request: GetCharacterSoundRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CharacterSound:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacterSound",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterSoundRequest,
                output=CharacterSound,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_dialogue_transitions(
        self,
        request: ListDialogueTransitionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListDialogueTransitionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDialogueTransitions",
                service_name="bgvoice.v1.PipelineService",
                input=ListDialogueTransitionsRequest,
                output=ListDialogueTransitionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_dialogue_transition(
        self,
        request: GetDialogueTransitionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DialogueTransition:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDialogueTransition",
                service_name="bgvoice.v1.PipelineService",
                input=GetDialogueTransitionRequest,
                output=DialogueTransition,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_portraits(
        self,
        request: ListPortraitsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListPortraitsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPortraits",
                service_name="bgvoice.v1.PipelineService",
                input=ListPortraitsRequest,
                output=ListPortraitsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_portrait(
        self,
        request: GetPortraitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Portrait:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPortrait",
                service_name="bgvoice.v1.PipelineService",
                input=GetPortraitRequest,
                output=Portrait,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def download_portrait(
        self,
        request: DownloadPortraitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PortraitContent:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DownloadPortrait",
                service_name="bgvoice.v1.PipelineService",
                input=DownloadPortraitRequest,
                output=PortraitContent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_races(
        self,
        request: ListRacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListRacesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRaces",
                service_name="bgvoice.v1.PipelineService",
                input=ListRacesRequest,
                output=ListRacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_race(
        self,
        request: GetRaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Race:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRace",
                service_name="bgvoice.v1.PipelineService",
                input=GetRaceRequest,
                output=Race,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_character_classes(
        self,
        request: ListCharacterClassesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCharacterClassesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCharacterClasses",
                service_name="bgvoice.v1.PipelineService",
                input=ListCharacterClassesRequest,
                output=ListCharacterClassesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_character_class(
        self,
        request: GetCharacterClassRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CharacterClass:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCharacterClass",
                service_name="bgvoice.v1.PipelineService",
                input=GetCharacterClassRequest,
                output=CharacterClass,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_kits(
        self,
        request: ListKitsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListKitsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKits",
                service_name="bgvoice.v1.PipelineService",
                input=ListKitsRequest,
                output=ListKitsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_kit(
        self,
        request: GetKitRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Kit:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKit",
                service_name="bgvoice.v1.PipelineService",
                input=GetKitRequest,
                output=Kit,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_identifier_definitions(
        self,
        request: ListIdentifierDefinitionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListIdentifierDefinitionsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListIdentifierDefinitions",
                service_name="bgvoice.v1.PipelineService",
                input=ListIdentifierDefinitionsRequest,
                output=ListIdentifierDefinitionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_identifier_definition(
        self,
        request: GetIdentifierDefinitionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> IdentifierDefinition:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetIdentifierDefinition",
                service_name="bgvoice.v1.PipelineService",
                input=GetIdentifierDefinitionRequest,
                output=IdentifierDefinition,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_campaigns(
        self,
        request: ListCampaignsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListCampaignsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCampaigns",
                service_name="bgvoice.v1.PipelineService",
                input=ListCampaignsRequest,
                output=ListCampaignsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_campaign(
        self,
        request: GetCampaignRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Campaign:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCampaign",
                service_name="bgvoice.v1.PipelineService",
                input=GetCampaignRequest,
                output=Campaign,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_extraction_runs(
        self,
        request: ListExtractionRunsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ListExtractionRunsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListExtractionRuns",
                service_name="bgvoice.v1.PipelineService",
                input=ListExtractionRunsRequest,
                output=ListExtractionRunsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_extraction_run(
        self,
        request: GetExtractionRunRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExtractionRun:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetExtractionRun",
                service_name="bgvoice.v1.PipelineService",
                input=GetExtractionRunRequest,
                output=ExtractionRun,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
