# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import BaseModel as _BaseModel, ConfigDict as _ConfigDict, Field as _Field

from ._proto_types import ProtoInt64, ProtoTimestamp, ProtoUInt64, _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class View(_ProtoEnum):
    VIEW_UNSPECIFIED = ("VIEW_UNSPECIFIED", 0)
    VIEW_BASIC = ("VIEW_BASIC", 1)
    VIEW_FULL = ("VIEW_FULL", 2)


class SourceKind(_ProtoEnum):
    SOURCE_KIND_UNSPECIFIED = ("SOURCE_KIND_UNSPECIFIED", 0)
    SOURCE_KIND_OVERRIDE = ("SOURCE_KIND_OVERRIDE", 1)
    SOURCE_KIND_BIF = ("SOURCE_KIND_BIF", 2)
    SOURCE_KIND_DLC = ("SOURCE_KIND_DLC", 3)


class DetailStatus(_ProtoEnum):
    DETAIL_STATUS_UNSPECIFIED = ("DETAIL_STATUS_UNSPECIFIED", 0)
    DETAIL_STATUS_PENDING = ("DETAIL_STATUS_PENDING", 1)
    DETAIL_STATUS_COMPLETE = ("DETAIL_STATUS_COMPLETE", 2)
    DETAIL_STATUS_FAILED = ("DETAIL_STATUS_FAILED", 3)


class AttributionStatus(_ProtoEnum):
    ATTRIBUTION_STATUS_UNSPECIFIED = ("ATTRIBUTION_STATUS_UNSPECIFIED", 0)
    ATTRIBUTION_STATUS_MATCHED = ("ATTRIBUTION_STATUS_MATCHED", 1)
    ATTRIBUTION_STATUS_PARTIAL_MATCH = ("ATTRIBUTION_STATUS_PARTIAL_MATCH", 2)
    ATTRIBUTION_STATUS_MISSING_DIALOGUE = ("ATTRIBUTION_STATUS_MISSING_DIALOGUE", 3)
    ATTRIBUTION_STATUS_NO_DIALOGUE = ("ATTRIBUTION_STATUS_NO_DIALOGUE", 4)
    ATTRIBUTION_STATUS_CHARACTER_UNAVAILABLE = ("ATTRIBUTION_STATUS_CHARACTER_UNAVAILABLE", 5)


class AttributionPublicationStatus(_ProtoEnum):
    ATTRIBUTION_PUBLICATION_STATUS_UNSPECIFIED = ("ATTRIBUTION_PUBLICATION_STATUS_UNSPECIFIED", 0)
    ATTRIBUTION_PUBLICATION_STATUS_MISSING = ("ATTRIBUTION_PUBLICATION_STATUS_MISSING", 1)
    ATTRIBUTION_PUBLICATION_STATUS_STALE = ("ATTRIBUTION_PUBLICATION_STATUS_STALE", 2)
    ATTRIBUTION_PUBLICATION_STATUS_PUBLISHED = ("ATTRIBUTION_PUBLICATION_STATUS_PUBLISHED", 3)


class DialogueLineKind(_ProtoEnum):
    DIALOGUE_LINE_KIND_UNSPECIFIED = ("DIALOGUE_LINE_KIND_UNSPECIFIED", 0)
    DIALOGUE_LINE_KIND_NPC = ("DIALOGUE_LINE_KIND_NPC", 1)
    DIALOGUE_LINE_KIND_PLAYER = ("DIALOGUE_LINE_KIND_PLAYER", 2)
    DIALOGUE_LINE_KIND_JOURNAL = ("DIALOGUE_LINE_KIND_JOURNAL", 3)


class IdentifierKind(_ProtoEnum):
    IDENTIFIER_KIND_UNSPECIFIED = ("IDENTIFIER_KIND_UNSPECIFIED", 0)
    IDENTIFIER_KIND_RACE = ("IDENTIFIER_KIND_RACE", 1)
    IDENTIFIER_KIND_CLASS = ("IDENTIFIER_KIND_CLASS", 2)
    IDENTIFIER_KIND_GENDER = ("IDENTIFIER_KIND_GENDER", 3)
    IDENTIFIER_KIND_ALIGNMENT = ("IDENTIFIER_KIND_ALIGNMENT", 4)
    IDENTIFIER_KIND_ENEMY_ALLY = ("IDENTIFIER_KIND_ENEMY_ALLY", 5)
    IDENTIFIER_KIND_GENERAL = ("IDENTIFIER_KIND_GENERAL", 6)
    IDENTIFIER_KIND_SPECIFIC = ("IDENTIFIER_KIND_SPECIFIC", 7)
    IDENTIFIER_KIND_ANIMATION = ("IDENTIFIER_KIND_ANIMATION", 8)
    IDENTIFIER_KIND_KIT = ("IDENTIFIER_KIND_KIT", 9)
    IDENTIFIER_KIND_SOUND_SLOT = ("IDENTIFIER_KIND_SOUND_SLOT", 10)


class RunKind(_ProtoEnum):
    RUN_KIND_UNSPECIFIED = ("RUN_KIND_UNSPECIFIED", 0)
    RUN_KIND_CHARACTERS = ("RUN_KIND_CHARACTERS", 1)
    RUN_KIND_DIALOGUES = ("RUN_KIND_DIALOGUES", 2)
    RUN_KIND_PORTRAITS = ("RUN_KIND_PORTRAITS", 3)
    RUN_KIND_METADATA = ("RUN_KIND_METADATA", 4)
    RUN_KIND_ATTRIBUTION = ("RUN_KIND_ATTRIBUTION", 5)


class RunStatus(_ProtoEnum):
    RUN_STATUS_UNSPECIFIED = ("RUN_STATUS_UNSPECIFIED", 0)
    RUN_STATUS_RUNNING = ("RUN_STATUS_RUNNING", 1)
    RUN_STATUS_COMPLETE = ("RUN_STATUS_COMPLETE", 2)
    RUN_STATUS_COMPLETE_WITH_ERRORS = ("RUN_STATUS_COMPLETE_WITH_ERRORS", 3)
    RUN_STATUS_FAILED = ("RUN_STATUS_FAILED", 4)


class ResourceSource(_ProtoModel):
    kind: "SourceKind | None" = _Field(default=None)
    path: str = _Field(default="")


class ExtractionState(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    status: "DetailStatus | None" = _Field(default=None)
    error: str | None = _Field(default=None)
    updated_at: ProtoTimestamp | None = _Field(
        default=None,
        alias="updatedAt",
    )
    run: str = _Field(default="")


class PipelineSummary(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    voices: ProtoUInt64 = _Field(default=0)
    characters: ProtoUInt64 = _Field(default=0)
    dialogues: ProtoUInt64 = _Field(default=0)
    dialogue_lines: ProtoUInt64 = _Field(
        default=0,
        alias="dialogueLines",
    )
    character_sounds: ProtoUInt64 = _Field(
        default=0,
        alias="characterSounds",
    )
    dialogue_transitions: ProtoUInt64 = _Field(
        default=0,
        alias="dialogueTransitions",
    )
    races: ProtoUInt64 = _Field(default=0)
    character_classes: ProtoUInt64 = _Field(
        default=0,
        alias="characterClasses",
    )
    kits: ProtoUInt64 = _Field(default=0)
    identifier_definitions: ProtoUInt64 = _Field(
        default=0,
        alias="identifierDefinitions",
    )
    matched_characters: ProtoUInt64 = _Field(
        default=0,
        alias="matchedCharacters",
    )
    partially_matched_characters: ProtoUInt64 = _Field(
        default=0,
        alias="partiallyMatchedCharacters",
    )
    missing_dialogue_characters: ProtoUInt64 = _Field(
        default=0,
        alias="missingDialogueCharacters",
    )
    unattributed_dialogues: ProtoUInt64 = _Field(
        default=0,
        alias="unattributedDialogues",
    )
    unattributed_dialogue_lines: ProtoUInt64 = _Field(
        default=0,
        alias="unattributedDialogueLines",
    )


class Installation(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    database_path: str = _Field(
        default="",
        alias="databasePath",
    )
    database_size: ProtoUInt64 = _Field(
        default=0,
        alias="databaseSize",
    )
    attribution_publication: "AttributionPublicationStatus | None" = _Field(
        default=None,
        alias="attributionPublication",
    )
    attribution_completed_at: ProtoTimestamp | None = _Field(
        default=None,
        alias="attributionCompletedAt",
    )
    summary: "PipelineSummary | None" = _Field(default=None)


class CharacterReference(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    engine_resource_name: str = _Field(
        default="",
        alias="engineResourceName",
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    npc_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="npcLineCount",
    )


class DialogueReference(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    engine_resource_name: str = _Field(
        default="",
        alias="engineResourceName",
    )
    npc_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="npcLineCount",
    )


class Voice(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    voice_id: str = _Field(
        default="",
        alias="voiceId",
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    prompt: str = _Field(default="")
    characters: "list[CharacterReference]" = _Field(
        default_factory=list,
    )
    dialogues: "list[DialogueReference]" = _Field(
        default_factory=list,
    )
    portrait: str | None = _Field(default=None)
    character_count: int = _Field(
        default=0,
        alias="characterCount",
    )
    dialogue_count: int = _Field(
        default=0,
        alias="dialogueCount",
    )
    npc_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="npcLineCount",
    )
    serialized_size: ProtoUInt64 = _Field(
        default=0,
        alias="serializedSize",
    )
    biography: str | None = _Field(default=None)


class CharacterDialogueSummary(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    declared_dialogue_count: int = _Field(
        default=0,
        alias="declaredDialogueCount",
    )
    resolved_dialogue_count: int = _Field(
        default=0,
        alias="resolvedDialogueCount",
    )
    dialogue_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="dialogueLineCount",
    )
    npc_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="npcLineCount",
    )
    player_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="playerLineCount",
    )
    journal_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="journalLineCount",
    )
    state_count: ProtoUInt64 = _Field(
        default=0,
        alias="stateCount",
    )
    transition_count: ProtoUInt64 = _Field(
        default=0,
        alias="transitionCount",
    )
    serialized_size: ProtoUInt64 = _Field(
        default=0,
        alias="serializedSize",
    )


class CharacterClassLevels(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    first_class: int = _Field(
        default=0,
        alias="firstClass",
    )
    second_class: int = _Field(
        default=0,
        alias="secondClass",
    )
    third_class: int = _Field(
        default=0,
        alias="thirdClass",
    )


class CharacterBaseAttributes(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    strength: int = _Field(default=0)
    strength_bonus: int = _Field(
        default=0,
        alias="strengthBonus",
    )
    intelligence: int = _Field(default=0)
    wisdom: int = _Field(default=0)
    dexterity: int = _Field(default=0)
    constitution: int = _Field(default=0)
    charisma: int = _Field(default=0)


class CharacterDetail(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    short_name: str | None = _Field(
        default=None,
        alias="shortName",
    )
    short_name_strref: int = _Field(
        default=0,
        alias="shortNameStrref",
    )
    long_name: str | None = _Field(
        default=None,
        alias="longName",
    )
    long_name_strref: int = _Field(
        default=0,
        alias="longNameStrref",
    )
    death_variable: str | None = _Field(
        default=None,
        alias="deathVariable",
    )
    dialog_resref: str | None = _Field(
        default=None,
        alias="dialogResref",
    )
    gender_id: int = _Field(
        default=0,
        alias="genderId",
    )
    gender_label: str = _Field(
        default="",
        alias="genderLabel",
    )
    race_id: int = _Field(
        default=0,
        alias="raceId",
    )
    race_label: str = _Field(
        default="",
        alias="raceLabel",
    )
    race: str = _Field(default="")
    class_id: int = _Field(
        default=0,
        alias="classId",
    )
    class_label: str = _Field(
        default="",
        alias="classLabel",
    )
    character_class: str = _Field(
        default="",
        alias="characterClass",
    )
    alignment_id: int = _Field(
        default=0,
        alias="alignmentId",
    )
    alignment_label: str = _Field(
        default="",
        alias="alignmentLabel",
    )
    enemy_ally_id: int = _Field(
        default=0,
        alias="enemyAllyId",
    )
    enemy_ally_label: str = _Field(
        default="",
        alias="enemyAllyLabel",
    )
    general_id: int = _Field(
        default=0,
        alias="generalId",
    )
    general_label: str = _Field(
        default="",
        alias="generalLabel",
    )
    specific_id: int = _Field(
        default=0,
        alias="specificId",
    )
    specific_label: str = _Field(
        default="",
        alias="specificLabel",
    )
    animation_id: int = _Field(
        default=0,
        alias="animationId",
    )
    animation_label: str = _Field(
        default="",
        alias="animationLabel",
    )
    racial_enemy_id: int = _Field(
        default=0,
        alias="racialEnemyId",
    )
    racial_enemy_label: str = _Field(
        default="",
        alias="racialEnemyLabel",
    )
    cre_kit_value: int = _Field(
        default=0,
        alias="creKitValue",
    )
    kit_ids_value: int | None = _Field(
        default=None,
        alias="kitIdsValue",
    )
    kit_label: str | None = _Field(
        default=None,
        alias="kitLabel",
    )
    class_levels: "CharacterClassLevels | None" = _Field(
        default=None,
        alias="classLevels",
    )
    base_attributes: "CharacterBaseAttributes | None" = _Field(
        default=None,
        alias="baseAttributes",
    )
    morale: int = _Field(default=0)
    morale_break: int = _Field(
        default=0,
        alias="moraleBreak",
    )
    morale_recovery_time: int = _Field(
        default=0,
        alias="moraleRecoveryTime",
    )
    reputation: int = _Field(default=0)
    override_script: str | None = _Field(
        default=None,
        alias="overrideScript",
    )
    class_script: str | None = _Field(
        default=None,
        alias="classScript",
    )
    race_script: str | None = _Field(
        default=None,
        alias="raceScript",
    )
    general_script: str | None = _Field(
        default=None,
        alias="generalScript",
    )
    default_script: str | None = _Field(
        default=None,
        alias="defaultScript",
    )
    small_portrait_resref: str | None = _Field(
        default=None,
        alias="smallPortraitResref",
    )
    large_portrait_resref: str | None = _Field(
        default=None,
        alias="largePortraitResref",
    )
    cre_version: str = _Field(
        default="",
        alias="creVersion",
    )


class Character(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    engine_resource_name: str = _Field(
        default="",
        alias="engineResourceName",
    )
    resref: str = _Field(default="")
    display_name: str | None = _Field(
        default=None,
        alias="displayName",
    )
    voice: str | None = _Field(default=None)
    portrait: str | None = _Field(default=None)
    source: "ResourceSource | None" = _Field(default=None)
    extraction: "ExtractionState | None" = _Field(default=None)
    attribution_status: "AttributionStatus | None" = _Field(
        default=None,
        alias="attributionStatus",
    )
    serialized_size: ProtoUInt64 | None = _Field(
        default=None,
        alias="serializedSize",
    )
    dialogue: "CharacterDialogueSummary | None" = _Field(default=None)
    detail: "CharacterDetail | None" = _Field(default=None)
    direct_dialogue: str | None = _Field(
        default=None,
        alias="directDialogue",
    )
    biography: str | None = _Field(default=None)


class DialogueDetail(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    dlg_version: str = _Field(
        default="",
        alias="dlgVersion",
    )
    state_count: ProtoUInt64 = _Field(
        default=0,
        alias="stateCount",
    )
    transition_count: ProtoUInt64 = _Field(
        default=0,
        alias="transitionCount",
    )
    npc_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="npcLineCount",
    )
    player_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="playerLineCount",
    )
    journal_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="journalLineCount",
    )
    dialogue_line_count: ProtoUInt64 = _Field(
        default=0,
        alias="dialogueLineCount",
    )


class Dialogue(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    engine_resource_name: str = _Field(
        default="",
        alias="engineResourceName",
    )
    resref: str = _Field(default="")
    source: "ResourceSource | None" = _Field(default=None)
    extraction: "ExtractionState | None" = _Field(default=None)
    serialized_size: ProtoUInt64 | None = _Field(
        default=None,
        alias="serializedSize",
    )
    character_count: int = _Field(
        default=0,
        alias="characterCount",
    )
    detail: "DialogueDetail | None" = _Field(default=None)


class DialogueLine(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    dialogue: str = _Field(default="")
    dialogue_resref: str = _Field(
        default="",
        alias="dialogueResref",
    )
    source_kind: "SourceKind | None" = _Field(
        default=None,
        alias="sourceKind",
    )
    line_kind: "DialogueLineKind | None" = _Field(
        default=None,
        alias="lineKind",
    )
    state_index: int = _Field(
        default=0,
        alias="stateIndex",
    )
    state_trigger_index: int | None = _Field(
        default=None,
        alias="stateTriggerIndex",
    )
    state_trigger_text: str | None = _Field(
        default=None,
        alias="stateTriggerText",
    )
    transition_index: int | None = _Field(
        default=None,
        alias="transitionIndex",
    )
    strref: int = _Field(default=0)
    text: str | None = _Field(default=None)
    tokens: list[str] = _Field(
        default_factory=list,
    )
    serialized_size: ProtoUInt64 = _Field(
        default=0,
        alias="serializedSize",
    )
    character_count: int = _Field(
        default=0,
        alias="characterCount",
    )


class CharacterSound(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    character: str = _Field(default="")
    character_display_name: str = _Field(
        default="",
        alias="characterDisplayName",
    )
    slot_id: int = _Field(
        default=0,
        alias="slotId",
    )
    slot_symbols: list[str] = _Field(
        default_factory=list,
        alias="slotSymbols",
    )
    slot_groups: list[str] = _Field(
        default_factory=list,
        alias="slotGroups",
    )
    strref: int = _Field(default=0)
    text: str | None = _Field(default=None)
    serialized_size: ProtoUInt64 = _Field(
        default=0,
        alias="serializedSize",
    )


class DialogueTransition(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    dialogue: str = _Field(default="")
    dialogue_resref: str = _Field(
        default="",
        alias="dialogueResref",
    )
    source_kind: "SourceKind | None" = _Field(
        default=None,
        alias="sourceKind",
    )
    state_index: int = _Field(
        default=0,
        alias="stateIndex",
    )
    transition_index: int = _Field(
        default=0,
        alias="transitionIndex",
    )
    flags_raw: int = _Field(
        default=0,
        alias="flagsRaw",
    )
    flags_decoded: list[str] = _Field(
        default_factory=list,
        alias="flagsDecoded",
    )
    trigger_index: int | None = _Field(
        default=None,
        alias="triggerIndex",
    )
    trigger_text: str | None = _Field(
        default=None,
        alias="triggerText",
    )
    action_index: int | None = _Field(
        default=None,
        alias="actionIndex",
    )
    action_text: str | None = _Field(
        default=None,
        alias="actionText",
    )
    next_dialogue_resref: str | None = _Field(
        default=None,
        alias="nextDialogueResref",
    )
    next_state_index: int | None = _Field(
        default=None,
        alias="nextStateIndex",
    )
    terminates_dialogue: bool = _Field(
        default=False,
        alias="terminatesDialogue",
    )
    serialized_size: ProtoUInt64 = _Field(
        default=0,
        alias="serializedSize",
    )
    next_dialogue: str | None = _Field(
        default=None,
        alias="nextDialogue",
    )


class Portrait(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    resref: str = _Field(default="")
    source: "ResourceSource | None" = _Field(default=None)
    width: int = _Field(default=0)
    height: int = _Field(default=0)
    media_type: str = _Field(
        default="",
        alias="mediaType",
    )


class PortraitContent(_ProtoModel):
    portrait: str = _Field(default="")
    png: bytes = _Field(default=b"")


class RaceText(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    source_resource: str = _Field(
        default="",
        alias="sourceResource",
    )
    campaigns: list[str] = _Field(
        default_factory=list,
    )
    row_name: str | None = _Field(
        default=None,
        alias="rowName",
    )
    name_strref: int | None = _Field(
        default=None,
        alias="nameStrref",
    )
    display_name: str | None = _Field(
        default=None,
        alias="displayName",
    )
    description_strref: int | None = _Field(
        default=None,
        alias="descriptionStrref",
    )
    description: str | None = _Field(default=None)
    uppercase_name_strref: int | None = _Field(
        default=None,
        alias="uppercaseNameStrref",
    )
    uppercase_name: str | None = _Field(
        default=None,
        alias="uppercaseName",
    )
    biography_strref: int | None = _Field(
        default=None,
        alias="biographyStrref",
    )
    biography: str | None = _Field(default=None)


class Race(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    race_id: int = _Field(
        default=0,
        alias="raceId",
    )
    symbols: list[str] = _Field(
        default_factory=list,
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    texts: "list[RaceText]" = _Field(
        default_factory=list,
    )


class CharacterClassText(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    source_resource: str = _Field(
        default="",
        alias="sourceResource",
    )
    campaigns: list[str] = _Field(
        default_factory=list,
    )
    row_name: str | None = _Field(
        default=None,
        alias="rowName",
    )
    class_text_kit_id: int | None = _Field(
        default=None,
        alias="classTextKitId",
    )
    lower_name_strref: int | None = _Field(
        default=None,
        alias="lowerNameStrref",
    )
    lower_name: str | None = _Field(
        default=None,
        alias="lowerName",
    )
    description_strref: int | None = _Field(
        default=None,
        alias="descriptionStrref",
    )
    description: str | None = _Field(default=None)
    mixed_name_strref: int | None = _Field(
        default=None,
        alias="mixedNameStrref",
    )
    mixed_name: str | None = _Field(
        default=None,
        alias="mixedName",
    )
    biography_strref: int | None = _Field(
        default=None,
        alias="biographyStrref",
    )
    biography: str | None = _Field(default=None)
    fallen: bool | None = _Field(default=None)
    brief_description_strref: int | None = _Field(
        default=None,
        alias="briefDescriptionStrref",
    )
    brief_description: str | None = _Field(
        default=None,
        alias="briefDescription",
    )
    fallen_notice_strref: int | None = _Field(
        default=None,
        alias="fallenNoticeStrref",
    )
    fallen_notice: str | None = _Field(
        default=None,
        alias="fallenNotice",
    )


class CharacterClass(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    class_id: int = _Field(
        default=0,
        alias="classId",
    )
    symbols: list[str] = _Field(
        default_factory=list,
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    texts: "list[CharacterClassText]" = _Field(
        default_factory=list,
    )


class Kit(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    row_id: int = _Field(
        default=0,
        alias="rowId",
    )
    row_name: str = _Field(
        default="",
        alias="rowName",
    )
    source_resource: str = _Field(
        default="",
        alias="sourceResource",
    )
    lower_name: str | None = _Field(
        default=None,
        alias="lowerName",
    )
    mixed_name: str | None = _Field(
        default=None,
        alias="mixedName",
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )
    help_text: str | None = _Field(
        default=None,
        alias="helpText",
    )
    character_class: str | None = _Field(
        default=None,
        alias="characterClass",
    )
    class_symbols: list[str] = _Field(
        default_factory=list,
        alias="classSymbols",
    )
    kit_ids_value: int | None = _Field(
        default=None,
        alias="kitIdsValue",
    )
    kit_symbols: list[str] = _Field(
        default_factory=list,
        alias="kitSymbols",
    )
    abilities_resref: str | None = _Field(
        default=None,
        alias="abilitiesResref",
    )
    proficiency_column: int | None = _Field(
        default=None,
        alias="proficiencyColumn",
    )
    unusable_mask: int | None = _Field(
        default=None,
        alias="unusableMask",
    )


class IdentifierDefinition(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    kind: "IdentifierKind | None" = _Field(default=None)
    value: int = _Field(default=0)
    symbols: list[str] = _Field(
        default_factory=list,
    )
    source_resource: str = _Field(
        default="",
        alias="sourceResource",
    )
    display_name: str = _Field(
        default="",
        alias="displayName",
    )


class Campaign(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    campaign_id: str = _Field(
        default="",
        alias="campaignId",
    )
    ordinal: int = _Field(default=0)
    display_name: str = _Field(
        default="",
        alias="displayName",
    )


class ExtractionRun(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    name: str = _Field(default="")
    run_id: str = _Field(
        default="",
        alias="runId",
    )
    run_kind: "RunKind | None" = _Field(
        default=None,
        alias="runKind",
    )
    started_at: ProtoTimestamp | None = _Field(
        default=None,
        alias="startedAt",
    )
    completed_at: ProtoTimestamp | None = _Field(
        default=None,
        alias="completedAt",
    )
    status: "RunStatus | None" = _Field(default=None)
    resources_discovered: ProtoUInt64 = _Field(
        default=0,
        alias="resourcesDiscovered",
    )
    details_attempted: ProtoUInt64 = _Field(
        default=0,
        alias="detailsAttempted",
    )
    details_extracted: ProtoUInt64 = _Field(
        default=0,
        alias="detailsExtracted",
    )
    failures: ProtoUInt64 = _Field(default=0)
    error: str | None = _Field(default=None)


class GetInstallationRequest(_ProtoModel):
    name: str = _Field(default="")


class ListVoicesRequest(_ProtoModel):
    """
    Every List method uses the same read contract: page_size defaults to 25 and
    is capped at 100; page_token is an opaque cursor bound to the other request
    fields; filter accepts search("text") plus documented equality predicates;
    order_by accepts one documented field with an optional "desc" suffix; and
    an unspecified view means VIEW_BASIC. Search results keep BM25 relevance
    order unless order_by is explicitly set.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListVoicesResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    voices: "list[Voice]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetVoiceRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListCharactersRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListCharactersResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    characters: "list[Character]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetCharacterRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListDialoguesRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListDialoguesResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    dialogues: "list[Dialogue]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetDialogueRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListDialogueLinesRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListDialogueLinesResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    dialogue_lines: "list[DialogueLine]" = _Field(
        default_factory=list,
        alias="dialogueLines",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetDialogueLineRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListCharacterSoundsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListCharacterSoundsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    character_sounds: "list[CharacterSound]" = _Field(
        default_factory=list,
        alias="characterSounds",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetCharacterSoundRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListDialogueTransitionsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListDialogueTransitionsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    dialogue_transitions: "list[DialogueTransition]" = _Field(
        default_factory=list,
        alias="dialogueTransitions",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetDialogueTransitionRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListPortraitsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListPortraitsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    portraits: "list[Portrait]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetPortraitRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class DownloadPortraitRequest(_ProtoModel):
    name: str = _Field(default="")


class ListRacesRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListRacesResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    races: "list[Race]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetRaceRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListCharacterClassesRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListCharacterClassesResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    character_classes: "list[CharacterClass]" = _Field(
        default_factory=list,
        alias="characterClasses",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetCharacterClassRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListKitsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListKitsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    kits: "list[Kit]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetKitRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListIdentifierDefinitionsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListIdentifierDefinitionsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    identifier_definitions: "list[IdentifierDefinition]" = _Field(
        default_factory=list,
        alias="identifierDefinitions",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetIdentifierDefinitionRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListCampaignsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListCampaignsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    campaigns: "list[Campaign]" = _Field(
        default_factory=list,
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetCampaignRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)


class ListExtractionRunsRequest(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    parent: str = _Field(default="")
    page_size: int = _Field(
        default=0,
        alias="pageSize",
    )
    page_token: str = _Field(
        default="",
        alias="pageToken",
    )
    filter_: str = _Field(
        default="",
        alias="filter",
    )
    order_by: str = _Field(
        default="",
        alias="orderBy",
    )
    view: "View | None" = _Field(default=None)


class ListExtractionRunsResponse(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    extraction_runs: "list[ExtractionRun]" = _Field(
        default_factory=list,
        alias="extractionRuns",
    )
    next_page_token: str = _Field(
        default="",
        alias="nextPageToken",
    )
    total_size: ProtoInt64 = _Field(
        default=0,
        alias="totalSize",
    )


class GetExtractionRunRequest(_ProtoModel):
    name: str = _Field(default="")
    view: "View | None" = _Field(default=None)
